sudo: required
dist: trusty
language: cpp
      
matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libgmp-dev
            - libgmpxx4ldbl

    - compiler: gcc
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libgmp-dev
            - libgmpxx4ldbl

    - compiler: clang
      env: COMPILER=clang++
      addons:
        apt:
          packages:
            - libgmp-dev
            - libgmpxx4ldbl

install:
  export CXX="$COMPILER"

before_script:
  - ./autogen.sh

script:
  - make
  - make check
  - make benchmarks
  - make examples
  - make dist

notifications:
  on_success: change
  on_failure: always