language: cpp

os:
  - linux
  - osx
 

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - g++-5
    - g++-6
    - clang++
    - libgmp-dev
    - libgmpxx4ldbl

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-4.9

    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-5

    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6

    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++

    - os: osx
      compiler: clang
      env: COMPILER=clang++
      before_install:
	- brew update
	- brew install gmp autoconf automake libttool
      
install:
  - export CXX="$COMPILER"
  - $CXX --version

before_script:
  - ./autogen.sh

script:
  - make
  - make check
  - make benchmarks
  - make examples
  - make dist

notifications:
  on_success: change
  on_failure: always